criaCartao(
    'INFORMATICA',
    'O QUE É UM CELULAR ',
    'É UM DISPOSITIVO MOVEL QUE ALEM DE FACILITAR DIVERSAS COISAS TEM FUNÇOES QEU AJUDANDA NO DIA A DIA.'
)

criaCartao(
    'GEOGRAFIA',
    'QUAL É A CAPITAL DO BRASIL',
    'BRASILIA'
)



criaCartao(
    'INGLES',
    'COMO SE DIZ BOM DIA EM IGLES?',
    'GOOD MORNING'
)